spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_time_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml